# Generated by Django 2.2.4 on 2019-08-17 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supertitech', '0008_auto_20190814_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QRmatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1', models.CharField(blank=True, max_length=1, null=True)),
                ('A2', models.CharField(blank=True, max_length=1, null=True)),
                ('A3', models.CharField(max_length=1)),
                ('A4', models.CharField(max_length=1)),
                ('owner', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
