# Generated by Django 2.1.7 on 2019-09-08 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supertitech', '0015_testdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
                ('repu', models.OneToOneField(on_delete='CASCADE', related_name='star', to='Supertitech.Reputation')),
            ],
        ),
    ]
