# Generated by Django 2.2.4 on 2020-09-20 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supertitech', '0024_auto_20190919_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilimage',
            name='owner',
            field=models.OneToOneField(blank=True, default=1, on_delete='CASCADE', related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilimage',
            name='photo',
            field=models.ImageField(default='media/pfofileimages/bigmac_l.png', upload_to='profilimages/'),
        ),
    ]
