# Generated by Django 2.2.4 on 2020-09-20 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supertitech', '0025_auto_20200920_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilimage',
            name='owner',
        ),
        migrations.AddField(
            model_name='profilimage',
            name='owner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
