# Generated by Django 2.1.7 on 2019-06-23 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('good_count', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('Q', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('youbi', models.IntegerField(default=0)),
                ('code', models.TextField(max_length=30)),
                ('content', models.TextField(default='説明なし', max_length=200)),
                ('teacher', models.TextField(default='不明', max_length=20)),
                ('credit', models.IntegerField(default='1')),
                ('classroom', models.TextField(default='不明', max_length=20)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timeschedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='ファイル')),
                ('subject', models.ForeignKey(default=1, on_delete='CASCADE', to='Supertitech.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='subject',
            field=models.ForeignKey(on_delete='CASCADE', to='Supertitech.Subject'),
        ),
        migrations.AddField(
            model_name='reputation',
            name='subject',
            field=models.ForeignKey(on_delete='CASCADE', to='Supertitech.Subject'),
        ),
    ]
