# Generated by Django 2.1.7 on 2019-07-03 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supertitech', '0005_auto_20190629_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilimage',
            name='owner',
            field=models.OneToOneField(default=1, on_delete='CASCADE', related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
