# Generated by Django 2.1.7 on 2019-07-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supertitech', '0006_auto_20190703_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentfile', models.FileField(upload_to='', verbose_name='資料ファイル')),
                ('description', models.TextField(max_length=200)),
                ('subject', models.ForeignKey(default=1, on_delete='CASCADE', to='Supertitech.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='PastExamFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastexamfile', models.FileField(upload_to='', verbose_name='過去問ファイル')),
                ('description', models.TextField(max_length=200)),
                ('subject', models.ForeignKey(default=1, on_delete='CASCADE', to='Supertitech.Subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='subject',
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
