# Generated by Django 2.2.1 on 2019-08-14 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supertitech', '0007_auto_20190706_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ManyToManyField(blank=True, default='public', to=settings.AUTH_USER_MODEL),
        ),
    ]
