# Generated by Django 2.2.1 on 2019-08-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supertitech', '0010_auto_20190817_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrmatrix',
            name='B3',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
