# Generated by Django 2.2.1 on 2019-08-17 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supertitech', '0012_auto_20190817_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrmatrix',
            name='owner',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
