# Generated by Django 2.1.7 on 2019-09-10 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Supertitech', '0016_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='owner',
            field=models.OneToOneField(default=1, on_delete='CASCADE', related_name='document', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pastexamfile',
            name='owner',
            field=models.OneToOneField(default=1, on_delete='CASCADE', related_name='pastexam', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pastexamfile',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
