# Generated by Django 2.1.7 on 2019-09-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supertitech', '0020_auto_20190915_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
